protected/models/Company.php
<?php

/**
 * This is the model class for table "company".
 *
 * The followings are the available columns in table 'company':
 * @property integer $idCompany
 * @property integer $idManufacturer
 * @property Manufacturer $manufacturer
 *
 * @property integer $idCompanyClass
 * @property string $fullName
 * @property string $fullNameEng
 * @property string $shortName
 * @property string $city
 * @property string $cityGenetivus
 * @property string $physicalAddress
 * @property string $physicalAddressEng
 * @property string $legalAddress
 * @property string $url
 * @property string $email
 * @property string $phone
 * @property string $addPhone
 * @property string $comment
 * @property integer $enumFinanceType
 * @property string $inn
 * @property string $financeType
 * @property string $ogrn
 * @property string $bik
 * @property string $bankName
 * @property string $account
 * @property string $correspondentAccount
 *
 * @property Customer[] $customers
 */
class Company extends ActiveRecord implements IProvidesCustomizableColumns
{

    /**
     * Returns the static model of the specified AR class.
     * @param string $className active record class name.
     * @return Company the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function getIsManufacturerDescription()
    {
        return ($this->idManufacturer !== null);
    }

    function behaviors()
    {
        return array(
            'loggable' => array(
                'class' => 'ActiveRecordLoggable',
                'logCreation' => true,
                'shouldBubbleToMaster' => !true
            )
        );
    }

    public function getName()
    {
        return $this->shortName;
    }

    public function saveCustomers($new)
    {

        foreach ($this->customers as $customer) {
            $customer->idCompany = null;
            $customer->save();
        }

        foreach ($new as $customerId) {
            $customer = Customer::model()->findByPk($customerId);

            if ($customer) {

                $customer->idCompany = $this->idCompany;
                $customer->save();
            }
        }
    }

    public function getFinanceType()
    {
        $a = $this->getEnumFinanceTypeList();
        return $a[$this->enumFinanceType];
    }

    public static function getEnumFinanceTypeList()
    {
        return array(0 => 'Коммерческая стурктура',
            1 => 'Телефонный звонок',
            2 => 'Проведена первоначальная встреча',
            3 => 'Экскурсия на завод',
        );
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return 'company';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('abbr, fullName, idCompanyClass, shortName, city', 'required'),
            array('abbr', 'length', 'max' => 255),
            array('abbr', 'unique', 'allowEmpty' => false),
            array('enumFinanceType', 'numerical', 'integerOnly' => true),
            array('shortName,email, inn, ogrn, bik, bankName, account, correspondentAccount', 'length', 'max' => 64),
            array(' city, phone, addPhone', 'length', 'max' => 45),
            array('fullName, fullNameEng,  physicalAddressEng,  physicalAddress, legalAddress, url', 'length', 'max' => 255),
            array('url', 'url', 'defaultScheme' => 'http'),
            array('comment, fullNameEng,  physicalAddressEng, cityGenetivus, requisites', 'safe'),
            // The following rule is used by search().
            // Please remove those attributes that should not be searched.
            array('idCompany, abbr, fullName, shortName, city, physicalAddress, legalAddress, url, email, phone, addPhone, comment, enumFinanceType, inn, ogrn, bik, bankName, account, correspondentAccount', 'safe', 'on' => 'search'),
        );
    }

    public function beforeDelete()
    {

        if (Yii::app()->user->isGuest) {
            return false;
        }


        if (($this->manufacturer)) {
            $this->addError("", "Нельзя удалить, так как это описание производителя!");
            return false;
        }

        if (count($this->projectsAsBuyer) || (count($this->projectsAsConsumer))) {
            $this->addError("", "Нельзя удалить, так как используется в проектах!");
            return false;
        }


        if (!Group::getPermissionsUponZone(Group::ZONE_COMPANY,Group::ACTION_DELETE,$this)) {
            return !true;
        }

        return parent::beforeDelete();
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'customers' => array(self::HAS_MANY, 'Customer', 'idCompany'),
            'companyClass' => array(self::BELONGS_TO, 'CompanyClass', 'idCompanyClass'),
            'manufacturer' => array(self::BELONGS_TO, 'Manufacturer', 'idManufacturer'),
            'projectsAsBuyer' => array(self::HAS_MANY, 'Project', 'idCompanyBuyer'),
            'projectsAsConsumer' => array(self::HAS_MANY, 'Project', 'idCompanyConsumer'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'requisites' => 'Банковские реквизиты',
            'projectsAsConsumer' => 'Участие в пректах в качестве конечного пользователя',
            'projectsAsBuyer' => 'Участие в пректах в качестве поставщика',
            'companyClass' => 'Тип организации',
            'abbr' => 'Аббревиатура на латинском, для именования КП',
            'idCompany' => 'Id Company',
            'idCompanyClass' => 'Тип организации',
            'companyClass' => 'Тип организации',
            'fullName' => 'Полное наименование',
            'fullNameEng' => 'Полное наименование(на англ.)',
            'shortName' => 'Сокращенное наимаименование',
            'city' => 'Город',
            'cityGenetivus' => 'Город, в родительном падеже (доставка до Москвы)',
            'physicalAddress' => 'Физический адрес',
            'physicalAddressEng' => 'Физический адрес(на англ.)',
            'legalAddress' => 'Юридический адрес',
            'url' => 'Веб-сайт',
            'email' => 'Email',
            'phone' => 'Телефон',
            'addPhone' => 'Доп.телефон',
            'comment' => 'Комментарий',
            'enumFinanceType' => 'Тип финансирования',
            'inn' => 'ИНН',
            'ogrn' => 'ОГРН',
            'bik' => 'БИК',
            'bankName' => 'Название банка',
            'account' => 'Расчетный счет',
            'correspondentAccount' => 'Корреспондентский счет',
            'customers' => 'Список клиентов, сотрудников данной огранизации',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search()
    {
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('idCompany', $this->idCompany);
        $criteria->compare('idCompanyClass', $this->idCompanyClass);

        $criteria->compare('fullNameEng', $this->fullNameEng, true);

        $criteria->compare('fullName', $this->fullName, true);
        $criteria->compare('fullName', $this->shortName, true, 'OR');

        $criteria->compare('shortName', $this->fullName, true, 'OR');
        $criteria->compare('shortName', $this->shortName, true, 'OR');


        $criteria->compare('city', $this->city, true);

        $criteria->compare('physicalAddress', $this->physicalAddress, true);
        $criteria->compare('physicalAddressEng', $this->physicalAddressEng, true);
        $criteria->compare('legalAddress', $this->legalAddress, true);
        $criteria->compare('url', $this->url, true);
        $criteria->compare('email', $this->email, true);
        $criteria->compare('phone', $this->phone, true);
        $criteria->compare('addPhone', $this->addPhone, true);
        $criteria->compare('comment', $this->comment, true);
        $criteria->compare('enumFinanceType', $this->enumFinanceType);
        $criteria->compare('inn', $this->inn, true);
        $criteria->compare('ogrn', $this->ogrn, true);
        $criteria->compare('abbr', $this->abbr, true);
        $criteria->compare('bik', $this->bik, true);
        $criteria->compare('bankName', $this->bankName, true);
        $criteria->compare('account', $this->account, true);
        $criteria->compare('correspondentAccount', $this->correspondentAccount, true);

        if ($this->idCompanyClass==CompanyClass::MANUFACTURE_COMPANY_CLASS) {
            list($outUglySql, $additionalWithes) = Group::getUglySql(Group::ZONE_MANUFACTURER, True);
            $criteria->addCondition($outUglySql);
        }

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    /**
     * @return ARCustomizableColumnsBase
     */
    public function getCustomizableColumns()
    {
        return new CompanyCustomizableColumns();
    }
}

protected/controllers/CompanyController.php
<?php

class CompanyController extends Controller {
    public function getZone( ) {
        return Group::ZONE_COMPANY;
    }
    private $_allowAjax = true;
     public function filters() {
        return array(
            'accessControl',
        );
    } 

    public function accessRules() {
        return array(
            array('deny', // deny all users
                'users' => array('?'),
            ),
        );
    }
    public $layout = 'column1';

    public function actionIndex() {
        $model = new Company('search');
        $model->unsetAttributes();

        if (isset($_GET['Company']))
            $model->setAttributes($_GET['Company']);

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    public function actionIndexManufacturers() {
        $model = new Company('search');
        $model->unsetAttributes();

        if (isset($_GET['Company']))
            $model->setAttributes($_GET['Company']);

        //$model->idCompanyClass = CompanyClass::MANUFACTURE_COMPANY_CLASS;


        $this->render('adminManufacturers', array(
            'model' => $model,
        ));
    }
    
    public function actionView($id) {
        $model = $this->loadModel($id);

        if ($this->mGridViewDataProvider->renderPartialGridViewIfRequired(array('project-grid', 'customer-grid','project-grid-manufacturer'), $model)) {
            return;
        }

        $this->render("view",array('model'=>$model,
                                  ));
        
    }
    
    public function actionCreate() {
        $model = new Company;
        if (isset($_POST['Company'])) {
            $model->setAttributes($_POST['Company']);
            try {
                if ($model->save()) {
             //       $model->saveCustomers(isset($_POST['Company']['customers']) ? $_POST['Company']['customers'] : array());

                    if (($this->_allowAjax) && (Yii::app()->request->isAjaxRequest)) {
                        Helpers::headerJson();
                        exit(json_encode(array('result' => 'success', 'name' => $model->nameUrl, 'idCompany' => $model->idCompany)));
                    }

                    Yii::app()->user->setFlash('success', "Запись создана");
                    if (isset($_GET['returnUrl'])) {
                        $this->redirect($_GET['returnUrl']);
                    } else {
                        $this->redirect(array('index'));
                    }
                } else {
                    if (($this->_allowAjax) && (Yii::app()->request->isAjaxRequest)) {
                        Helpers::headerJson();
                        exit(json_encode(array('result' => 'error', 'msg' => $this->renderPartial('_lightweightForm', array(
                            'model' => $model), true))));
                    }
                }
            } catch (Exception $e) {
                $model->addError('', $e->getMessage());
            }
        } elseif (isset($_GET['Company'])) {
            $model->attributes = $_GET['Company'];
        }

        if (Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('_lightweightForm', array(
                'model' => $model,
                    ), false, true);
        } else {
            $this->render('create', array('model' => $model));
        }
    }

    //the controller action that handles the ajax request
    public function actionCreateAjax() {
        if (isset($_POST['Company'])) {
            $model = new Company();
            $model->unsetAttributes();
            $model->setAttributes($_POST['Company']);
            if (!$model->save())
                exit(json_encode(array('result' => 'error', 'msg' => $this->renderPartial('_lightweightForm', array(
                'model' => $model,
                    ), true)
                    
                    )));
            else
                exit(json_encode(array('result' => 'success', 'msg' => 'Your data has been successfully saved')));
        }else {
            exit(json_encode(array('result' => 'error', 'msg' => 'No input data has been passed.')));
        }
    }

    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        if (isset($_POST['Company'])) {
            $model->setAttributes($_POST['Company']);
            try {
                if ($model->save()) {
                    Yii::app()->user->setFlash('success', "Данные обновлены");
                    if (($this->_allowAjax) && (Yii::app()->request->isAjaxRequest)) {
                        Helpers::headerJson();
                        exit(json_encode(array('result' => 'success')));
                    }

                    if (isset($_GET['returnUrl'])) {
                        $this->redirect($_GET['returnUrl']);
                    } else {
                        $this->redirect($model->getViewUrl());
                    }
                } else {
                    if (($this->_allowAjax) && (Yii::app()->request->isAjaxRequest)) {
                        Helpers::headerJson();
                        exit(json_encode(array('result' => 'error', 'msg' => $this->renderPartial('_lightweightForm', array(
                            'model' => $model), true))));
                    }
                }
            } catch (Exception $e) {
                $model->addError('', $e->getMessage());
            }
        }

        if (Yii::app()->request->isAjaxRequest) {
            $this->renderPartial('_lightweightForm', array(
                'model' => $model,
            ), false, true);
        } else {
            $this->render('update', array('model' => $model));
        }
    }

    public function actionDelete($id) {
        if (Yii::app()->request->isPostRequest) {
            try {
                $this->loadModel($id)->delete();
            } catch (Exception $e) {
                throw new CHttpException(500, $e->getMessage());
            }

            if (!Yii::app()->getRequest()->getIsAjaxRequest()) {
                $this->redirect(array('index'));
            }
        }
        else
            throw new CHttpException(400,
                    Yii::t('app', 'Invalid request.'));
    }

    public function loadModel($id) {
        $model = Company::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, Yii::t('app', 'The requested page does not exist.'));
        return $model;
    }

}

protected/views/company/_form.php
<?php if (Yii::app()->user->hasFlash('success')): ?>

    <div class="alert-box success">
        <?php echo Yii::app()->user->getFlash('success'); ?>
        <a href="" class="close">&times;</a>
    </div>
<?php endif; ?>
    <div class="form">
        <p class="note">
            <?php echo Yii::t('app', 'Fields with'); ?> <span
                class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
        </p>

        <?php
        $form = $this->beginWidget('CActiveForm', array(
            'id' => 'company-form',
            'enableAjaxValidation' => false,
            'enableClientValidation' => true,
        ));

        echo $form->errorSummary($model);
        ?>


        <fieldset>

            <div class="row">
                <div class="six columns">
                    <?php echo $form->labelEx($model, 'fullName'); ?>
                    <?php echo $form->textField($model, 'fullName', array('size' => 60, 'maxlength' => 255)); ?>
                    <?php echo $form->error($model, 'fullName'); ?>


                    <?php echo $form->labelEx($model, 'shortName'); ?>
                    <?php echo $form->textField($model, 'shortName', array('size' => 45, 'maxlength' => 64)); ?>
                    <?php echo $form->error($model, 'shortName'); ?>

                    <?php echo $form->labelEx($model, 'abbr'); ?>
                    <?php echo $form->textField($model, 'abbr', array('size' => 45, 'maxlength' => 10)); ?>
                    <?php echo $form->error($model, 'abbr'); ?>
                </div>
                <div class="six columns">
                    <?php echo $form->labelEx($model, 'fullNameEng'); ?>
                    <?php echo $form->textField($model, 'fullNameEng', array('size' => 60, 'maxlength' => 255)); ?>
                    <?php echo $form->error($model, 'fullNameEng'); ?>

                    <?php echo $form->labelEx($model, 'city'); ?>
                    <?php echo $form->textField($model, 'city', array('size' => 45, 'maxlength' => 45)); ?>
                    <?php echo $form->error($model, 'city'); ?>

                    <?php echo $form->labelEx($model, 'cityGenetivus'); ?>
                    <?php echo $form->textField($model, 'cityGenetivus', array('size' => 45, 'maxlength' => 45)); ?>
                    <?php echo $form->error($model, 'cityGenetivus'); ?>

                    <div class="indent-bot-15">
                        <?php echo $form->labelEx($model, 'idCompanyClass'); ?>
                        <?php echo $form->dropDownList($model, 'idCompanyClass', CHtml::listData(CompanyClass::model()->findAll(), "idCompanyClass", "name")); ?>
                        <?php echo $form->error($model, 'idCompanyClass'); ?>
                    </div>
                </div>
            </div>

        </fieldset>
        <fieldset>
            <div class="row">
                <div class="six columns"><?php echo $form->labelEx($model, 'url'); ?>
                    <?php echo $form->textField($model, 'url', array('size' => 60, 'maxlength' => 255)); ?>
                    <?php echo $form->error($model, 'url'); ?>
                    <?php echo $form->labelEx($model, 'email'); ?>
                    <?php echo $form->textField($model, 'email', array('size' => 60, 'maxlength' => 64)); ?>
                    <?php echo $form->error($model, 'email'); ?>
                </div>
                <div class="six columns">
                    <?php echo $form->labelEx($model, 'phone'); ?>
                    <?php echo $form->textField($model, 'phone', array('size' => 45, 'maxlength' => 45)); ?>
                    <?php echo $form->error($model, 'phone'); ?>

                    <?php echo $form->labelEx($model, 'addPhone'); ?>
                    <?php echo $form->textField($model, 'addPhone', array('size' => 45, 'maxlength' => 45)); ?>
                    <?php echo $form->error($model, 'addPhone'); ?>
                </div>
            </div>
            <?php echo $form->labelEx($model, 'physicalAddress'); ?>
            <?php echo $form->textField($model, 'physicalAddress', array('size' => 60, 'maxlength' => 255)); ?>
            <?php echo $form->error($model, 'physicalAddress'); ?>

            <?php echo $form->labelEx($model, 'physicalAddressEng'); ?>
            <?php echo $form->textField($model, 'physicalAddressEng', array('size' => 60, 'maxlength' => 255)); ?>
            <?php echo $form->error($model, 'physicalAddressEng'); ?>


            <?php echo $form->labelEx($model, 'legalAddress'); ?>
            <?php echo $form->textField($model, 'legalAddress', array('size' => 60, 'maxlength' => 255)); ?>
            <?php echo $form->error($model, 'legalAddress'); ?>
        </fieldset>


        <?php echo $form->labelEx($model, 'requisites'); ?>
        <?php echo $form->textArea($model, 'requisites', array('rows' => 5)); ?>
        <?php echo $form->error($model, 'requisites'); ?>

        <?php echo $form->labelEx($model, 'comment'); ?>
        <?php echo $form->textArea($model, 'comment', array('rows' => 6, 'cols' => 50)); ?>
        <?php echo $form->error($model, 'comment'); ?>




        <?php
        echo CHtml::submitButton(Yii::t('app', 'Save'), array('class' => 'button'));

        if (!$model->isNewRecord) {
            echo "&nbsp;" . CHtml::link('Удалить', Yii::app()->createUrl("system/confirmDeletion", array(
                        "mid" => deletionHelper::D_COMPANY,
                        "id" => $model->getPrimaryKey()))
                    , array('class' => 'alert button del-btn'));
        }

        $this->endWidget();
        ?>
    </div> <!-- form -->

<?php
$this->widget('ext.slidetoggle.ESlidetoggle', array(
    'itemSelector' => 'div.more',
    'titleSelector' => 'div.more h6',
    'collapsed' => 'div.more',
    'duration' => 'fast'
));
?>

protected/views/company/_lightweightForm.php
<?php
$form_name = 'sticky-ajax-form';
$form = $this->beginWidget('ext.foundation.widgets.FounActiveForm', array(
    'id' => $form_name,
    'htmlOptions' => array(
        'onsubmit' => "sendFormAjax('#$form_name'); return false;",
    ),
    'enableAjaxValidation' => false,
    'enableClientValidation' => true,
));

?>

<script>
    function sendFormAjax(form) {
        window.dwDialog.uploadForm(form, "<?= Yii::app()->request->getRequestUri() ?>", false);
    }
</script>

<fieldset>
    <?php if ($model->isNewRecord) { ?>
        <legend>Создать компанию</legend>
    <?php } ?>
    <?php echo $form->errorSummary($model); ?>
    <div class="row full-width">
        <div class="six columns">
            <?php echo $form->labelEx($model, 'fullName'); ?>
            <?php echo $form->textField($model, 'fullName', array('size' => 60, 'maxlength' => 255)); ?>
            <?php echo $form->error($model, 'fullName'); ?>
            <?php echo $form->labelEx($model, 'shortName'); ?>
            <?php echo $form->textField($model, 'shortName', array('size' => 45, 'maxlength' => 64)); ?>
            <?php echo $form->error($model, 'shortName'); ?>
            <?php echo $form->labelEx($model, 'abbr'); ?>
                <?php echo $form->textField($model, 'abbr', array('size' => 45, 'maxlength' => 10)); ?>
                <?php echo $form->error($model, 'abbr'); ?>
        </div>
        <div class="six columns">

            <?php echo $form->labelEx($model, 'city'); ?>
            <?php echo $form->textField($model, 'city', array('size' => 45, 'maxlength' => 45)); ?>
            <?php echo $form->error($model, 'city'); ?>

            <div class="indent-bot-15">
                <?php echo $form->labelEx($model, 'idCompanyClass'); ?>
                <?php echo $form->dropDownList($model, 'idCompanyClass', CHtml::listData(CompanyClass::model()->findAll(), "idCompanyClass", "name")); ?>
                <?php echo $form->error($model, 'idCompanyClass'); ?>
            </div>

        </div>
    </div>
    <div class="row full-width">
        <div class="twelve columns">
            <?php echo $form->labelEx($model, 'physicalAddress'); ?>
            <?php echo $form->textField($model, 'physicalAddress', array('size' => 60, 'maxlength' => 255)); ?>
            <?php echo $form->error($model, 'physicalAddress'); ?>

            <?php echo $form->labelEx($model, 'legalAddress'); ?>
            <?php echo $form->textField($model, 'legalAddress', array('size' => 60, 'maxlength' => 255)); ?>
            <?php echo $form->error($model, 'legalAddress'); ?>
        </div>
    </div>
    <div class="row full-width">
        <div class="six columns"><?php echo $form->labelEx($model, 'url'); ?>
            <?php echo $form->textField($model, 'url', array('size' => 60, 'maxlength' => 255)); ?>
            <?php echo $form->error($model, 'url'); ?>
            <?php echo $form->labelEx($model, 'email'); ?>
            <?php echo $form->textField($model, 'email', array('size' => 60, 'maxlength' => 64)); ?>
            <?php echo $form->error($model, 'email'); ?>
        </div>
        <div class="six columns">
            <?php echo $form->labelEx($model, 'phone'); ?>
            <?php echo $form->textField($model, 'phone', array('size' => 45, 'maxlength' => 45)); ?>
            <?php echo $form->error($model, 'phone'); ?>

            <?php echo $form->labelEx($model, 'addPhone'); ?>
            <?php echo $form->textField($model, 'addPhone', array('size' => 45, 'maxlength' => 45)); ?>
            <?php echo $form->error($model, 'addPhone'); ?>
        </div>
    </div>

</fieldset>

<?php
echo CHtml::submitButton($model->isNewRecord ? 'Создать' : 'Cохранить'
    , array('class' => 'button'));?>

<?php
$this->endWidget();
?>

protected/views/company/admin.php
<?php
$this->breadcrumbs = array(
    Yii::t('app', 'Companies')
);
?><header> <h3> Управление организациями </h3> </header>
<div class="indent-bot-20">
    <a class="button" href='<?= $this->createUrl("Company/create") ?> '>Создать новую организацию</a>
</div>

<?php
$this->widget('MGridView', array(
    'id' => 'company-grid',
    'dataProvider' => $model->search(),
    'filter' => $model,
    'cssFile' => false,
    'template' => '{items} {pager}',
    'columns' => array(

        array('class' => 'CButtonColumn',
            'template' => '{view}',
            'buttons' => array(
                'delete' => array(
                    'imageUrl' => Yii::app()->getBaseUrl() . '/images/icn_trash.png',
                    'options' => array('class' => 'button secondary tiny delete')
                ),
                'view' => array(
                    'imageUrl' => Yii::app()->getBaseUrl() . '/images/icn_edit.png',
                    'options' => array('class' => 'button secondary tiny view')
                ),
            ),
        ),
    ),
));
?>

protected/views/company/adminManufacturers.php
<?php
$this->breadcrumbs = array(
    Yii::t('app', 'Companies')=>"/company/index",
    "Производители оборудования"
);
?><header> <h3> Контакты производителей оборудования</h3> </header>


<?php
$this->widget('MGridView', array(
    'id' => 'company-grid',
    'dataProvider' => $model->search(),
    'filter' => $model,
    'cssFile' => false,
    'template' => '{items} {pager}',
    'columns' => array(

        array('class' => 'CButtonColumn',
            'template' => '{view}',
            'buttons' => array(
                'delete' => array(
                    'imageUrl' => Yii::app()->getBaseUrl() . '/images/icn_trash.png',
                    'options' => array('class' => 'button secondary tiny delete')
                ),
                'view' => array(
                    'imageUrl' => Yii::app()->getBaseUrl() . '/images/icn_edit.png',
                    'options' => array('class' => 'button secondary tiny view')
                ),
            ),
        ),
    ),
));
?>

protected/views/company/create.php
<?php
$this->breadcrumbs = array(
    Yii::t('app', 'Companies') => array('index'),
    Yii::t('app', 'Create'),
);?>
<header> <h3> Создать организацию </h3> </header>

<div class="module_content">
    
<?php
$this->renderPartial('_form', array(
			'model' => $model,
			'buttons' => 'create'));

?>
</div>

protected/views/company/view.php
<?php Yii::app()->clientScript->registerScriptFile("/js/revealActivate.js", CClientScript::POS_END); ?>

<?php
if ($model->isManufacturerDescription) {
    $this->breadcrumbs = array(
        Yii::t('app', 'Companies')=>"/company/index",
        "Производители оборудования"=>"/company/indexManufacturers",
        $model->shortName,
    );
} else {
$this->breadcrumbs = array(
    Yii::t('app', 'Companies') => array('index'),
    $model->shortName,
);
}
/* @var $model Customer */


$cols = array(
    array('shortName', 'city', 'phone', 'addPhone', 'abbr'),
    array('physicalAddress', 'legalAddress'),
);
?>

<h3> <?= (Group::getPermissionsUponZone(Group::ZONE_COMPANY,Group::ACTION_UPDATE,$model)) ? CHtml::link($model->fullName . ' ' . CHtml::image(Yii::app()->getBaseUrl() . '/images/pencil.png', 'Редактировать'), array('company/update', 'id' => $model->idCompany)) : $model->fullName ?>  </h3>

<div class="row">
    <div class="six columns">
        <?php
        foreach ($cols[0] as $attribute) {
            echo Helpers::reutrnTitleAndValueIfNotNull($model->getAttributeLabel($attribute), $model->getAttribute($attribute));
        }
        ?>
    </div>
    <div class="six columns">
        <?php
        echo Helpers::reutrnTitleAndValueIfNotNull($model->getAttributeLabel("idCompanyClass"), $model->idCompanyClass ? ($model->companyClass->name) : '');
        foreach ($cols[1] as $attribute) {
            echo Helpers::reutrnTitleAndValueIfNotNull($model->getAttributeLabel($attribute), $model->getAttribute($attribute));
        }
        echo Helpers::reutrnTitleAndValueIfNotNull($model->getAttributeLabel("url"), $model->url ? (CHtml::link($model->url, CHtml::normalizeUrl($model->url))) : '');
        ?>

    </div>
</div>
<?php if (($model->comment)) { ?>
    <fieldset>
        <legend>Комментарий</legend>
        <?= Helpers::getProcessedText($model->comment) ?><br/><br/>
    </fieldset>
<?php } ?>
<?php if (!$model->isManufacturerDescription) { ?>
<br/>
<div class="indent-bot-15">
    <?= CHtml::link('Создать проект для ' . $model->shortName, array('/project/create', 'Project[idCompanyConsumer]' => $model->idCompany), array('class' => 'button secondary')) ?>
</div>
<?php } ?>
<br/>
<h5> Сотрудники данной организации </h5>

<div class="indent-bot-20">
    <a class="button dwDialogTrigger" forceReload="true" target="_blank" href='<?= $this->createUrl("Customer/create",array('Customer[idCompany]'=>$model->idCompany)) ?> '>Создать нового сотрудника</a>
</div>

<?php
$this->mGridViewDataProvider->renderMGridView('customer-grid',$model);
?>

<?php if (!$model->isManufacturerDescription) { ?>
<h5> Проекты c участием данной организации </h5>

<?php
$this->mGridViewDataProvider->renderMGridView('company-view-project-grid',$model);
?>
<?php } else { ?>
    <h5> Проекты c участием данного производителя</h5>
    <?php
    $this->mGridViewDataProvider->renderMGridView('project-grid-manufacturer',$model);
    ?>
<?php } ?>